language: german

# Link to home
url: /

# link to github repo
# github_editme_path: https://github.com/tomjohnson1492/documentation-theme-jekyll-next-version/blob/gh-pages/
image_path: docs_de/images/

top_navbar_color: inverse
#blue --> use "inverse"
#black --> use "default"

highlighting_css: monokai
# options: "monokai" (black), "syntax" (white)

image_path: /docs_de/images/
navbar_style: darktheme
# navbar_logo: /docs_de/images/samplelogo.png

port: 4002
highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs_de:
    output: true
  tags_de:
    output: true

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      tag_group: taglist_de
  -
    scope:
      path: ""
      type: docs_de
    values:
      layout: default
      topnav: topnav_de
      tag_group: taglist_de
  -
    scope:
      path: ""
      type: tags_de
    values:
      layout: default
      topnav: topnav_de
      sidebar: taglist_de
      toc: false
      github_button: false
      search: false

exclude:
  - Gemfile
  - Gemfile.lock
  - index_en.md
  - index_ja.md

########## UI text ###############

uistring:
    title: Jekyll Dokumentation Theme # Displays as site title on top nav bar and on site metadata
    description: Dokumentationsthema für Jekyll-Webseiten # Displays as site description meta
    search_placeholder: Suche ...
    minitoc_title: Inhaltsverzeichnis
    github_edit_button_text: Bearbeiten Sie diese Seite
    search_results_page_title: Suchergebnisse
    search_placeholder_global: G Oba l Sayre rch ...
    search_placeholder_product: P Rodzu ct Sayre rch ...
    tags_title: es war gs
    tag_terms:
      product: Produkt
      page: Seite
      excerpt: Auszug
      tag_page_intro: Die folgenden Seiten sind markiert
